var worksList = [
	{	
		id: 0,
		title: "Tribute Page",
		description: "The first web page created by me dedicated to Mahatma Gandhi.",
		linkToDemo: "https://stepan20000.github.io/tribute-page.html",
		image: "images/portfolio-ver-0/tribute-page.png",
	},
	{	
		id: 1,
		title: "This portfolio",
		description: 'Made on pure HTML/CSS/JavaScript with dynamically created "Works" section.',
		linkToDemo: "https://stepan20000.github.io/portfolio-ver-0.html",
		image: "images/portfolio-ver-0/portfolio-ver-0.png",
	},
	{	
		id: 2,
		title: "This Random Quote Machine",
		description: 'The realization of <a href="https://www.freecodecamp.com/challenges/build-a-random-quote-machine">"Build a Random Quote Machine"</a> Intermediate Front End Development Projects on FreeCodeCamp.',
		linkToDemo: "https://stepan20000.github.io/random-quote-machine.html",
		image: "images/portfolio-ver-0/random-quote-machine.png",
	},
	{
		id: 3,
		title: "Show the Local Weather",
		description: 'The realization of <a href="https://www.freecodecamp.com/challenges/show-the-local-weather">"Show the Local Weather"</a> Intermediate Front End Development Projects on FreeCodeCamp.',
		linkToDemo: "https://stepan20000.github.io/show-the-local-weather.html",
		image: "images/portfolio-ver-0/show-the-local-weather.png",
	},
		{	
		id: 4,
		title: "Wikipedia Search",
		description: 'The realization of Intermediate Front End Development Project <a href="https://www.freecodecamp.com/challenges/build-a-wikipedia-viewer">"Build a Wikipedia Viewer"</a> on FreeCodeCamp',
		linkToDemo: "https://stepan20000.github.io/wikipedia-viewer.html",
		image: "images/portfolio-ver-0/wikipedia-viewer.png",
	},
	{	
		id: 5,
		title: "Twitchtv JSON API",
		description: 'The realization of <a href="https://www.freecodecamp.com/challenges/use-the-twitchtv-json-api" target="-blank">"Use the Twitchtv JSON API"</a> task on freeCodeCamp',
		linkToDemo: "https://stepan20000.github.io/twitchtv.html",
		image: "images/portfolio-ver-0/twitchtv.png",
	},
	{	
		id: 6,
		title: "JavaScript Calculator",
		description: 'The realization of <a href="https://www.freecodecamp.com/challenges/build-a-javascript-calculator" target="-blank">"Build a JavaScript Calculator"</a> task on freeCodeCamp. Implemented on pure JavaScript.',
		linkToDemo: "https://stepan20000.github.io/calculator.html",
		image: "images/portfolio-ver-0/calculator.png",
	},
	{	
		id: 7,
		title: "Pomodoro Timer",
		description: 'The realization of <a href="https://www.freecodecamp.com/challenges/build-a-pomodoro-clock" target="-blank">"Build a Pomodoro Clock"</a> task on freeCodeCamp. Created using jQuery',
		linkToDemo: "https://stepan20000.github.io/pomodoro.html",
		image: "images/portfolio-ver-0/pomodoro.png",
	},
	{	
		id: 8,
		title: "Tic Tac Toe Game",
		description: 'The realization of <a href="https://www.freecodecamp.com/challenges/build-a-tic-tac-toe-game" target="-blank">"Build a Tic Tac Toe Game "</a> task on freeCodeCamp.',
		linkToDemo: "https://stepan20000.github.io/tic-tac-toe.html",
		image: "images/portfolio-ver-0/tic-tac-toe.png",
	},
		{	
		id: 9,
		title: "Simon Game",
		description: 'The realization of <a href="https://www.freecodecamp.com/challenges/build-a-simon-game" target="-blank">"Build a Simon Game"</a> task on freeCodeCamp.',
		linkToDemo: "https://stepan20000.github.io/simon.html",
		image: "images/portfolio-ver-0/simon.png",
	},
    {
      id: 10,
      title: "Barbershop",
      description: 'The implementation of popular task of making web pages layout based on PSD files. BEM metodology is used',
      linkToDemo: "https://stepan20000.github.io/barbershop/index.html",
      image: "images/portfolio-ver-0/barbershop.png",
    }
];